### ISSUE TITLE
unsupported type interface {}

### ISSUE THREAD

**Issue by Rambatino** [kelindar/binary#12]
Hello! 👋 

We have data of the form:

``` go
type NotificationData struct {
	Metadata map[string]interface{}
}

// Notification model
type Notification struct {
	Data NotificationData
}
```

And it breaks with:

``` bash
unsupported type interface {}
```

Is this something you would consider supporting?

Can try and get a repeatable example if you need!

**Comment by kelindar** [comment]
Hi, unfortunately no, this library is by design not supporting untyped data types, as it doesn't embed type information in. 

You can either write a custom marshaler for this (i.e implement BinaryMarshal interface) or use some other package.

**Comment by Rambatino** [comment]
@kelindar Thank you for getting back to me! :)
