### ISSUE TITLE
Tags, Ignore Field

### ISSUE THREAD

**Issue by nanohard** [kelindar/binary#2]
It does not look like there is a way to ignore struct fields using tags such as `json:"-"`
Tried to use as a drop-in replacement to encoding/json and got `unsupported type *thirdParty.Struct`.

Is ignoring struct fields a feature that is on the roadmap?

**Comment by kelindar** [comment]
Interesting, I think we could solve it two ways:

1. Support tags, something like `binary:"-"`.
2. Add a codec for resolving pointers and encoding their values.

I'll add the binary capability first.
